version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '25432:5432'
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '23306:3306'
