version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
